name: 'JSON to Environment Variable -- With Masking. Node 16 compatable'
author: 'Anton Ivanenko, Roberto García, Charles Laing'
description: 'This action reads json file and writes its content as environment variables with optional secret masking'
branding:
  icon: 'lock'
  color: 'red'
inputs:
  filename: 
    description: 'The json file.'
    required: true
  prefix:
    description: 'The prefix for variables.'
    required: false
    default: 'json'
  masked:
    description: 'Mask variables as secrets.'
    required: false
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
